// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Authentication API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/ikueisou/apigateway/auth/design
// --force=true
// --out=$(GOPATH)/src/github.com/ikueisou/apigateway/auth/src
// --version=v1.3.1

package app
